output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false

ignore:
  - ^docs/

frosted:
    run: true

pyroma:
  run: true

pylint:
  disable:
    - W0141
    - R0903
  options:
    max-line-length: 120

pep8:
  full: true
  disable:
    - E126
  options:
    max-line-length: 120
