language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "travis_retry pip install nose coverage coveralls"
  - "travis_retry pip install git+https://github.com/landscapeio/pylint-plugin-utils.git@develop"
  - "travis_retry pip install git+https://github.com/landscapeio/pylint-common.git@develop"
  - "travis_retry pip install git+https://github.com/landscapeio/pylint-celery.git@develop"
  - "travis_retry pip install git+https://github.com/landscapeio/pylint-django.git@develop"
  - "travis_retry pip install git+https://github.com/landscapeio/requirements-detector.git@develop"
  - "travis_retry pip install --editable ."
script:
  - "nosetests -s --with-coverage --cover-inclusive --cover-package=prospector tests/"
  - "mv .coverage .coverage.x"
  - "travis_retry pip install -e .[with_everything]"
  - "coverage run --parallel-mode prospector/run.py || true"
  - "coverage combine"
  - "coverage report --show-missing"
after_success:
  coveralls
